version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR..
      - pip uninstall awscli  
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install --update 
      - rm -f awscliv2.zip  
      - aws --version
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCOUNT=192259153015
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com  
      - REPOSITORY_URI=${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/darkphoton
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo building material-sense on `date`
      - echo building docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URL:${IMAGE_TAG}
  post_build:
    commands:
      - echo building material-sense complete on `date`
      - echo pushing docker image...
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:${IMAGE_TAG}
